tasks:
  - name: Setup
    init: |
      pip install pre-commit && pre-commit install && npm install
    command: |
      make install generate
ports:
  - port: 8000
    onOpen: open-preview
vscode:
  extensions:
    - golang.Go
    - eamodio.gitlens
    - shd101wyy.markdown-preview-enhanced
