project_name: snipkit
before:
  hooks:
    - go mod download
builds:
  - id: macos
    env:
      - CGO_ENABLED=0
    goos: [ darwin ]
    goarch: [ amd64, arm64 ]
    flags:
      - "-tags={{ if index .Env \"BUILD_TAGS\"  }}{{ .Env.BUILD_TAGS }}{{ else }}\"\"{{ end }}"
  - id: linux
    env:
      - CGO_ENABLED=0
    goos: [ linux ]
    goarch: [ amd64, arm64, 386, arm ]
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
brews:
  - repository:
      owner: lemoony
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: https://github.com/lemoony/snipkit
    description: Access snippets from your favorite snippet manager without leaving the terminal
    #  skip_upload: auto
    test: |
      system "#{bin}/snipkit", "--version"
nfpms:
  -
    builds: [linux]
    homepage: https://github.com/lemoony/snipkit
    maintainer: Philipp Sessler <sessler.phil@googlemail.com>
    description: Access snippets from your favorite snippet manager without leaving the terminal.
    license: Apache 2.0
    formats:
      - deb
      - apk
      - rpm
