project_name: snipkit
before:
  hooks:
    - go mod download
builds:
- env:
    - CGO_ENABLED=0
  goos:
    - darwin
    - linux
  goarch:
    - amd64
brews:
- tap:
    owner: lemoony
    name: homebrew-tap
  folder: Formula
  homepage: https://github.com/lemoony/snippet-kit
  description: Access snippets from your favorite snippet manager without leaving the terminal.
#  skip_upload: auto
  test: |
    system "#{bin}/snipkit", "--version"
