version: 1.0.0
variables:
  textDefaultColor: ""
  textSelectionColor: "#f8f8f2"
  selectionBackgroundColor: "#ff5555"
  fieldBackgroundColor: "gray"
  secondaryFieldBackgroundColor: "lightgray"
  secondaryFieldTextColor: "gray"
theme:
  backgroundColor: ""
  borderColor: ""
  borderTitleColor:
  previewColorSchemeName: friendly
  previewApplyMainBackground: true
  previewOverwriteBackgroundColor: ""
  previewDefaultTextColor: ""
  itemTextColor: ${textDefaultColor}
  selectedItemTextColor: ${textSelectionColor}
  selectedItemBackgroundColor: ${selectionBackgroundColor}
  itemHighlightMatchBackgroundColor: ""
  itemHighlightMatchTextColor: "#50fa7b"
  counterTextColor: "#B79103"
  lookupInputTextColor: ${textDefaultColor}
  lookupInputPlaceholderColor: "#6272a4"
  lookupInputBackgroundColor: ""
  parametersLabelTextColor: ${textDefaultColor}
  parametersFieldBackgroundColor: ${fieldBackgroundColor}
  parametersFieldTextColor: ${textDefaultColor}
  selectedButtonBackgroundColor: ${selectionBackgroundColor}
  selectedButtonTextColor: ${textSelectionColor}
  parameterAutocompleteBackgroundColor: ${secondaryFieldBackgroundColor}
  parameterAutocompleteTextColor: ${secondaryFieldTextColor}
  parameterAutocompleteSelectedBackgroundColor: ${selectionBackgroundColor}
  parameterAutocompleteSelectedTextColor: ${textSelectionColor}