name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  goreleaser:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: "Docker login"
        run: docker login docker.pkg.github.com -u docker -p ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        run: make release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAP_GITHUB_TOKEN: ${{ secrets.TAP_GITHUB_TOKEN }}

      - name: Publish to apt
        run: |
          for i in dist/*.deb; do
            curl --fail -F package=@${i} "https://${PUSH_TOKEN}@push.fury.io/lemoony/"
          done
        env:
          PUSH_TOKEN: ${{ secrets.GEMFURY_PUSH_TOKEN }}
